# Generated by Django 2.0.2 on 2018-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='item_photo/')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
