# Generated by Django 2.0.2 on 2018-03-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180310_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_photo/')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_photo/')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('acronyms', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('stats_gems_enchants', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('talents', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('rotation_priority', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('legendaries', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('gear', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('trinkets', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('weak_auras', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('hero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Hero')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
