# Generated by Django 2.0.2 on 2018-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180310_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='character_photo/')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='hero',
        ),
        migrations.AddField(
            model_name='specialization',
            name='character',
            field=models.CharField(blank=True, choices=[('Warrior', 'Warrior'), ('DK', 'Death Knight'), ('DH', 'Demon Hunter'), ('Druid', 'Druid'), ('Hunter', 'Hunter'), ('Mage', 'Mage'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Priest', 'Priest'), ('Rogue', 'Rogue'), ('Shaman', 'Shaman'), ('Warlock', 'Warlock')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specialization_photo/'),
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='character',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, related_name='specializations', to='main.Specialization'),
        ),
    ]
